### ISSUE TITLE
Varied Outputs

### ISSUE THREAD

**Issue by Inshal240** [muhammadyaseen/CheckersGameTurboC#2]
Judging from a previously stated issue, it seems the program is working fine. But the output I receive on my machine varies greatly. The pieces don't move properly and the highlighted boxes remain highlighted. I'll look into it later tonight. Just thought I'd report it if anyone else was having the same problem.

<strong>Output</strong>
![shot_131016_141350](https://f.cloud.github.com/assets/5384262/1341120/65bfde0c-3643-11e3-891b-4c6897996ff9.png)

**Comment by muhammadyaseen** [comment]
@Rex240 Make sure you have the latest changes from repo before you start working, The 'X' mark should now be gone.

**Comment by Inshal240** [comment]
No wonder I was having a hard time debugging -.- That's s day lost. Anyways, closing the issue.
