### ISSUE TITLE
Change of BkColor

### ISSUE THREAD

**Issue by Wajiimalik** [muhammadyaseen/CheckersGameTurboC#3]
I tried playing Game several times and whenever Pieces move to 2nd row's right hand corner the background screen turns yellow.

![blue](https://f.cloud.github.com/assets/5440823/1367562/42fa3aca-3940-11e3-9d6f-1ec03f537ee1.jpg)

**Comment by muhammadyaseen** [comment]
I know the reason I believe, I'll update the issue as soon as I finish the work on `board` branch

**Comment by Inshal240** [comment]
I believe this has been solved long ago. Closing the issue.
