### ISSUE TITLE
A I ~ Red's turn but it can not move!

### ISSUE THREAD

**Issue by Wajiimalik** [muhammadyaseen/CheckersGameTurboC#9]
![untitled](https://f.cloud.github.com/assets/5440823/1443444/d3b570c8-41e4-11e3-8747-ca34f4598fc8.jpg)

**Comment by Inshal240** [comment]
Yes, this is probably where the game should end in a stalemate. We need to check after every turn whether the next person's moves are possible. If they're not, then the game should end in a `Draw`. I'll try to come up with something as this is quite similar to what I did in the AI implementation.

**Comment by Wajiimalik** [comment]
Both the issues are resolved. Closing both.
